Updated metadata
ex-phone-number/ex_phone_number pull request #81
Opened 2024-09-06 09:50 UTC by jbnoblot

Sync with new metadata file https://github.com/google/libphonenumber/commit/6896204d3777945f341678d0079f1ecbe58a0800

2024-09-06 11:45 UTC, szymon-jez requested changes
Please model your PR after this one https://github.com/ex-phone-number/ex_phone_number/pull/77/files (Notice also the PR name).

2024-09-06 12:30 UTC, jbnoblot commented
Hello,
Oups :/ you alright sorry. I made this as soon as possible

2024-09-06 12:43 UTC, jbnoblot commented
I hope it's good. Sorry again for bad PR model

2024-09-12 13:26 UTC, swiatkiewicz commented
Hi @szymon-jez, can we merge and release this update please?

2024-09-16 08:07 UTC, szymon-jez approved these changes

2024-09-16 08:07 UTC, merged

2024-09-16 08:33 UTC, szymon-jez commented
Released in https://hex.pm/packages/ex_phone_number/0.4.5.